import fs from "node:fs";
import path from "node:path";
import { $ } from "bun";

export async function runMigrationTest(
	tempDir: string,
	schemaContent: string,
): Promise<{ sqlContent: string; cleanup: () => Promise<void> }> {
	if (fs.existsSync(tempDir)) fs.rmSync(tempDir, { recursive: true });
	fs.mkdirSync(tempDir, { recursive: true });

	const schemaPath = path.join(tempDir, "schema.ts");
	fs.writeFileSync(schemaPath, schemaContent);

	const buildResult = await Bun.build({
		entrypoints: [schemaPath],
		outdir: path.join(tempDir, "out"),
		target: "node",
		format: "esm",
		external: [
			"drizzle-orm",
			"drizzle-orm/sqlite-core",
			"@artefact/schemascript",
		],
		define: {
			"process.env.BUILD_TARGET": JSON.stringify("SQLite"),
		},
	});

	if (!buildResult.success) {
		throw new Error(
			`Build failed: ${buildResult.logs.map((l) => l.message).join("\n")}`,
		);
	}

	const bundledPath = path.join(tempDir, "out", "schema.js");
	const migrationDir = path.join(tempDir, "migrations");

	// Hardcoding logic to satisfy the bundled output without macro dependencies
	let bundled = fs.readFileSync(bundledPath, "utf8");

	// Replace the bundled code that would have been generated by the macro or value.ts
	bundled = bundled.replace(
		/Constant\(\)/g,
		"({ now: { __type: 'sql', value: 'CURRENT_TIMESTAMP' } })",
	);
	bundled = bundled.replace(
		/\bvalue\.now\b/g,
		"({ __type: 'sql', value: 'CURRENT_TIMESTAMP' })",
	);

	fs.writeFileSync(bundledPath, bundled);

	const genResult =
		await $`bun x drizzle-kit generate --dialect sqlite --schema ${bundledPath} --out ${migrationDir}`.nothrow();

	if (genResult.exitCode !== 0) {
		throw new Error(
			`Migration generation failed: ${genResult.stderr.toString()}`,
		);
	}

	const migrationFiles = fs
		.readdirSync(migrationDir)
		.filter((f) => f.endsWith(".sql"));
	if (migrationFiles.length === 0) {
		throw new Error("No migration files generated");
	}

	const sqlContent = fs.readFileSync(
		path.join(migrationDir, migrationFiles[0]),
		"utf8",
	);

	return {
		sqlContent,
		cleanup: async () => {
			if (fs.existsSync(tempDir)) fs.rmSync(tempDir, { recursive: true });
		},
	};
}
