image: oven/bun:latest

stages:
  - test
  - build
  - publish

variables:
  BUN_INSTALL_DIR: /usr/local/bin

before_script:
  - apt-get update && apt-get install -y git
  - bun install --frozen-lockfile

test:
  stage: test
  script:
    - bun test --coverage --coverage-reporter=text --coverage-reporter=lcov --reporter=junit --reporter-outfile=junit.xml
  coverage: '/All files\s*\|\s*(\d+(?:\.\d+)?)/'

publish-dry-run:
  stage: test
  script:
    - bun run publish --dry-run
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == "main"'
  artifacts:
    when: always
    paths:
      - coverage/
    reports:
      junit: junit.xml

build:
  stage: build
  script:
    - bun run build
  artifacts:
    paths:
      - dist/
      - out/

publish:
  stage: publish
  script:
    - bun run publish --access public
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+/'
      when: always
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - package.json
      when: manual
      allow_failure: true

publish-alpha:
  stage: publish
  script:
    - bun run publish --access public --tag alpha
  rules:
    - if: '$CI_COMMIT_BRANCH == "alpha"'
      when: always
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: manual
      allow_failure: true
